export { LandingPage } from './LandingPage'
export type { LandingPageProps } from './LandingPage'
export { LandingHeader } from './LandingHeader'
export { LandingHero } from './LandingHero'
export { LandingProblem } from './LandingProblem'
export { LandingLoop } from './LandingLoop'
export { LandingVerticais } from './LandingVerticais'
export { LandingPatient } from './LandingPatient'
export { LandingProfessional } from './LandingProfessional'
export { LandingAIDiagnostic } from './LandingAIDiagnostic'
export { LandingTrust } from './LandingTrust'
export { LandingPricing } from './LandingPricing'
export { LandingTestimonials } from './LandingTestimonials'
export { LandingFAQ } from './LandingFAQ'
export { LandingFinalCTA } from './LandingFinalCTA'
export { LandingFooter } from './LandingFooter'
